# Generated by Django 4.2.7 on 2024-02-28 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category_id', models.CharField(max_length=50, unique=True)),
                ('category_image', models.ImageField(default=None, upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=50)),
                ('merchant_name', models.CharField(max_length=255)),
                ('merchant_mobile_no', models.CharField(max_length=15)),
                ('seller_id', models.CharField(default=None, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('user_comment', models.TextField(blank=True, default='', null=True)),
                ('order_date', models.DateField()),
                ('mail_status', models.BooleanField(default=False)),
                ('order_processed', models.CharField(choices=[('0', 'Pending'), ('1', 'Confirmed'), ('2', 'Delivered'), ('3', 'Cancelled')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=50)),
                ('product_details', models.TextField()),
                ('product_image', models.ImageField(default=None, upload_to='product_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiApp.category', to_field='category_id')),
            ],
        ),
    ]
